### ISSUE TITLE
Login issue since the update

### ISSUE THREAD

**Issue by Dyr-Fenrir** [Jetsurf/nso-api#6]
Greetings,

I was using the old version of the app and noticed that I was no longer able to login, figured it was linked to the recent maintenance so I went and installed the new nso-api version.

Since I installed it, I no longer seem to be able to login:
```
PS G:\Program Files\Python\Nintendo Switch Online\nso-api> python .\nso-cli.py --login
Unknown option argument!
Usage: .\nso-cli.py [options] <category> <command>
       .\nso-cli.py [options] <category> --help
       .\nso-cli.py [options] --login
Categories are: app account s2 s3 acnh
Options are:
  --user-data-file <filename>   Use the given file for user-specific token data (default 'nso_tokens.json')
```

I also tried with the actual option `--user-data-file`:
```
PS G:\Program Files\Python\Nintendo Switch Online\nso-api> python .\nso-cli.py --user-data-file nso_tokens.json --login
Unknown option argument!
Usage: .\nso-cli.py [options] <category> <command>
       .\nso-cli.py [options] <category> --help
       .\nso-cli.py [options] --login
Categories are: app account s2 s3 acnh
Options are:
  --user-data-file <filename>   Use the given file for user-specific token data (default 'nso_tokens.json')
```

And (using '' in `-user-data-file`):
```
PS G:\Program Files\Python\Nintendo Switch Online\nso-api> python .\nso-cli.py --user-data-file 'nso_tokens.json' --login
Unknown option argument!
Usage: .\nso-cli.py [options] <category> <command>
       .\nso-cli.py [options] <category> --help
       .\nso-cli.py [options] --login
Categories are: app account s2 s3 acnh
Options are:
  --user-data-file <filename>   Use the given file for user-specific token data (default 'nso_tokens.json')
```

I noticed that there was some changes, maybe this is an unwanted bug.

I am on Windows 11 (might a be an OS related bug).

May you help me out with this please?

Thank you again for your time and help, it is greatly appreciated!

**Comment by Jetsurf** [comment]
The NSO app updated to version 2.8.0 and changed the authentication process. This is the quick fix for now as the old process is allowed. Once iMink is updated to support 2.8.0, a long-term fix will be put in place.

Update to the latest git commit (`git pull` -> `pip3 install .`) and then add a line in your code similar to this commented line in example.py

https://github.com/Jetsurf/nso-api/blob/462ce1dfc20a4713c4a27bc42f6320d0da26a080/example.py#L39

That should get your scripts working for now.

**Comment by Dyr-Fenrir** [comment]
Greetings,

I kind of have a "déjà vu" here:
```
PS G:\Program Files\Python\Nintendo Switch Online\nso-api> python .\example.py
Login challenge URL: CENSORED
Paste login URL here:
CENSORED
<PreparedRequest [POST]>
POST https://accounts.nintendo.com/connect/1.0.0/api/session_token
User-Agent: OnlineLounge/2.7.1 NASDKAPI Android
Accept-Encoding: gzip
Accept: application/json
Connection: Keep-Alive
Accept-Language: en-US
Content-Type: application/x-www-form-urlencoded
Host: accounts.nintendo.com
Content-Length: 503

client_id=CENSORED&session_token_code=CENSORED&session_token_code_verifier=CENSORED
<Response [400]>
400 Bad Request
Content-Type: application/json; charset=utf-8
Content-Length: 92
Server: nginx
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=2592000; includeSubDomains
Expires: Fri, 01 Dec 2023 02:11:04 GMT
Pragma: no-cache
Date: Fri, 01 Dec 2023 02:11:04 GMT
Connection: close
Cache-Control: private, no-cache, must-revalidate, no-store
Set-Cookie: _abck=CENSORED Domain=.nintendo.com; Path=/; Expires=Sat, 30 Nov 2024 02:11:04 GMT; Max-Age=31536000; Secure, bm_sz=CENSORED; Domain=.nintendo.com; Path=/; Expires=Fri, 01 Dec 2023 06:11:04 GMT; Max-Age=14400

{"error_description":"The provided session_token_code is invalid","error":"invalid_request"}
Traceback (most recent call last):
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\example.py", line 57, in <module>
    if not nso.complete_login_challenge(input):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\nso_api\nso_api.py", line 507, in complete_login_challenge
    if not result.get('session_token'):
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
I updated to the latest version as instructed and added the line you specified.

**Comment by Jetsurf** [comment]
Looks like _that_ fix got yoinked at some point. It'll be back in place in a bit.

**Comment by Jetsurf** [comment]
iMink has been updated and everything's back to working as expected. Shouldn't need to make any modifications to have everything work again!

Can you give it a shot again and make sure everything's set for you?

**Comment by Dyr-Fenrir** [comment]
Greetings,

Sorry for the delay, I was not at home and could not test until now, I confirm that everything is working on my end!

Thank you a lot again for your time and help, it is, as always, greatly appreciated!
